[package]
name = "lrngitd"
version = "0.1.0"
edition = "2024"

[dependencies]
lrngitcore = { version = "0.1.0", path = "../lib" }
nix = {version = "0.30.1", features = ["process"]}
syscalls = "0.6.18"
